sudo: required
dist: xenial
services:
  - docker
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-generic-extra dvipng texlive-lang-german texlive-lang-english texlive-science
script:
  - mkdir -p build/Content
  - pdflatex -interaction=nonstopmode -halt-on-error -output-directory build thesis.tex
